whisper_only:
  default: false
  type: bool
show_in_read_restricted_categories:
  default: true
  type: bool
show_in_group_pms:
  default: true
  type: bool
restrict_to_groups:
  default: ""
  type: list
  list_type: group
restrict_to_categories:
  default: ""
  type: list
  list_type: category
